"""empty message

Revision ID: faa04078c464
Revises: 203a5c44da0a
Create Date: 2022-04-01 14:02:38.593620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa04078c464'
down_revision = '203a5c44da0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'content')
    # ### end Alembic commands ###
